# Generated by Django 5.2.6 on 2025-12-21 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0004_topic_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['order', 'date_added']},
        ),
        migrations.AddField(
            model_name='entry',
            name='title',
            field=models.CharField(default='untitled', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
