# Generated by Django 4.2.30 on 2026-04-23 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0006_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='img_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
